<?php
	echo '<?xml version="1.0" encoding="UTF-8" ?>';
	echo $this->doctype(); 
?>

<html>
	<head>
		<meta http-equiv="Content-Type" context="text/html"; charset="UTF-8">
		<?php
			echo $this->headTitle();
			echo $this->headScript();
			$this->loadSkin($this->skin);			// View helper LoadSkin
			echo $this->headLink();
		?>
		
	</head>


<body>


 <div class="page_margins">
    <div class="page">
    
      <!-- begin: #header -->
	  <div id="header">
      	<h1>H1</h1>
      </div>
	  
	  <!-- begin: #nav -->
	  <?php include("nav.phtml"); ?>      

      
      <!-- begin: #breadcrumbs -->  
	  <div class="breadcrumbs">
	    <?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" \ "); ?>
	  </div>

      
      <!--  begin: #main -->      
      <div id="main">
      
		<div id="col1">
          <div id="col1_content" class="clearfix">
            <?php echo $this->layout()->content; ?>&nbsp;
          </div>
        </div>
        <div id="col2">
          <div id="col2_content" class="clearfix">
            <p>Contenido de la subdivision derecha</p>
          </div>
        </div>
        <div id="col3">
          <div id="col3_content" class="clearfix">
            <p>Contenido de la subdivision izquierda</p>
          </div>
          <!-- IE Column Clearing -->
          <div id="ie_clearing"> &#160; </div>
        </div>      
        
      </div>


	  <!-- begin: #footer -->
	  <?php include("footer.phtml"); ?>

    </div>
 </div>


</body>
</html>