<?php
	echo '<?xml version="1.0" encoding="UTF-8" ?>';
	echo $this->doctype(); 
?>

<html>
	<head>
		<meta http-equiv="Content-Type" context="text/html"; charset="UTF-8">
		<?php
			echo $this->headTitle();
			echo $this->headScript();

			// Add a link to the site style sheet
			//$this->headLink()->appendStylesheet('/css/layout.css');
			$this->loadSkin($this->skin);
			echo $this->headLink();
		?>
		
	</head>


<body>
	<p><?php echo $this->miDato; ?></p>

	<div id="pageWrapper">
		<div id="header">
			<h1>Zend Framework CMS</h1>
		</div>
		<div class="nav">			
			<?php echo $this->navigation()->menu(); ?>
		</div>
		
		<div class="breadcrumbs">
			<?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" \ "); ?>
		</div>		
		
		
		<div id="sidebar">
			<div id="subNav">
				<?php echo $this->layout()->subNav;?>&nbsp;
			</div>
			<div id="adminMenu">
				<?php echo $this->layout()->adminMenu;?>&nbsp;
			</div>
			<div id="userForm">
				<?php echo $this->layout()->userForm;?>&nbsp;
			</div>
		</div>
		
		<div id="main">
			<?php echo $this->layout()->content;?>&nbsp;
		</div>
		
		<div id="footer">
			<p>
				Created with <a href="http://framework.zend.com/">
				Zend Framework</a>. Licensed under
				<a href="http://www.creativecommons.org/">Creative Commons</a>.
			</p>
		</div>
		
		
	</div>

<div class="page_margins">
    <div class="page">
      <div id="header">
      </div>
      <div id="nav">
        <!-- skiplink anchor: navigation -->
        <a id="navigation" name="navigation"></a>
        <div class="hlist">
          <?php echo $this->navigation()->menu(); ?>
          <!-- main navigation: horizontal list -->
         </div>
      </div>
      
      <!--  begin: #main -->      
      <div id="main">
        <div id="col1">
          <div id="col1_content" class="clearfix">
            <?php echo $this->layout()->content; ?>&nbsp;
          </div>
        </div>
        <div id="col3">
          <div id="col3_content" class="clearfix">
            <!-- add your content here -->
            
          </div>
          <!-- IE Column Clearing -->
          <div id="ie_clearing"> &#160; </div>
        </div>
      </div>

      <!-- begin: #footer -->
      <div id="footer">Layout based on <a href="http://www.yaml.de/">YAML</a>
      </div>
    </div>
  </div>


</body>
</html>