<?php
	echo '<?xml version="1.0 ?>';
	echo $this->doctype(); 
?>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="es" lang="es">

	<head>
		<meta http-equiv="Content-Type" context="text/html";>
		<?php
			echo $this->headTitle();
			echo $this->headScript();
			$this->loadSkin($this->skin);			// View helper LoadSkin
			echo $this->headLink();
		?>
		
	</head>


<body>


 <div class="page_margins">
    <div class="page">
    
      <!-- begin: #header -->
	  <div id="header">
      	<h1>H1</h1>
      </div>
	  
	  <!-- begin: #nav -->
	  <?php include("nav.phtml"); ?>      

      
      <!-- begin: #breadcrumbs -->  
	  <div class="breadcrumbs">
	    <?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" \ "); ?>
	  </div>

      
      <!--  begin: #main -->      
      <div id="main">
      
        <div id="col1">
          <div id="col1_content" class="clearfix">
          
          	<!--  Main view content -->
	        <?php echo $this->layout()->content; ?>&nbsp;
	        
	        <!--  begin: YAML subColumns -->
	        <div class="subcolumns">
			  <div class="c50l">
			    <div class="subcl">
			      <p>Contenido de la subdivision izquierda</p>
			    </div>
			  </div>
			
			  <div class="c50r">
			    <div class="subcr">
			      <p>Contenido de la subdivision derecha</p>
			    </div>
			  </div>		        
        	</div>
        	<!--  end: YAML subColumns -->
        	       
          </div>
        </div>
        
        <div id="col3">
          <div id="col3_content" class="clearfix">
		    <?php echo $this->layout()->sideCol;?>&nbsp;
          </div>
          <!-- IE Column Clearing -->
          <div id="ie_clearing"> &#160; </div>
        </div>
        
      </div>


	  <!-- begin: #footer -->
	  <?php include("footer.phtml"); ?>

    </div>
 </div>


</body>
</html>