
<div class="subcolumns">
	<div class="c80l">
		<div class="subcl">
			<h2>Diarios de viaje</h2>
			<p>Relatos de viajes destacados publicados o actualizados recientemente.<br>
			Hay <?= $this->numDiarios ?> <?php if ($this->numDiarios > 1) echo "diarios"; else echo "diario"; ?> (21.606 capitulos)</p>
		</div>
	</div>
			
	<div class="c20r">
		<div class="subcr">
			<div class="boton">
				<a href="http://www.viajeros.com/usuarios/registro.html"></a>
			</div>
		</div>
	</div>		        
</div>
        	
<br>

<table>
	<tr>
		<th>Num.</th>
		<th>Titulo</th>
		<th>Descripci&oacuten</th>
	</tr>
	<?php echo $this->partialLoop('index/table-row.phtml', $this->users); ?>
</table>