
<div class="subcolumns">
	<div class="c80l">
		<div class="subcl">
			<h2>Diarios de viaje</h2>
			<p>Relatos de viajes destacados publicados o actualizados recientemente.<br>
			Hay <?= $this->numDiarios ?> <?php if ($this->numDiarios > 1) echo "diarios"; else echo "diario"; ?> (21.606 capitulos)</p>
		</div>
	</div>
			
	<div class="c20r">
		<div class="subcr">
			<div class="boton">
				<a href="http://www.viajeros.com/usuarios/registro.html">Escribir un diario</a>
			</div>
		</div>
	</div>		        
</div>
        	
<br>

<table>
	<tr>
		<th>Num.</th>
		<th>Titulo</th>
		<th>Descripci&oacuten</th>
	</tr>
	<?php echo $this->partialLoop('index/table-row.phtml', $this->users); ?>
</table>


<div class="recuadro recuadro-destacado clearfix ">
	<h2>¿Adónde quieres viajar?</h2>
		<form accept-charset="UTF-8" id="form-buscar-destino" name="buscar-destino" method="get" action="http://www.viajeros.com/buscar/buscar">
			<fieldset>
				<input type="hidden" name="t" value="destinos">
				<input type="text" name="q" class="texto ml5 grid_5 js-autocompletar-destino js-autosubmit" style="font-size:1.2em;" tip="Escribe el nombre de una ciudad o país. Pausa para ver sugerencias" id="q-FIE6" autocomplete="off"><input type="hidden" name="q-id" id="q-id" value="">
				<button type="submit" class="big">&nbsp;¡Buscar! »&nbsp;</button>
			</fieldset>
		</form>
	<div class="clear" style="height:10px;">&nbsp;</div>
</div>